import { createContext } from "react";

export default createContext({
  userName: "",
  isModeAdmin: false,
  setIsModeAdmin: () => {},
  isCollapsed: false,
  setIsCollapsed: () => {},
  currentTabSelected: false,
  setCurrentTabSelected: () => {},
  menu: [],
  setMenu: () => {},
  handleAdd: () => {},
  handleDelete: () => {},
  resetMenu: () => {},
  newProduct: {},
  setNewProduct: () => {},
  productSelected: {},
  setProductSelected: () => {},
  handleEdit: () => {},
  titleEditRef: {},
  basket: [],
  handleAddToBasket: () => {},
  handleDeleteBasketProduct: () => {},
  handleProductSelected: () => {},
});
